# Generated by Django 5.2.4 on 2025-08-24 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity_in_stock', models.PositiveIntegerField(default=0)),
                ('low_stock_threshold', models.PositiveIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.category')),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='inventory_p_name_f6a6a1_idx'), models.Index(fields=['category'], name='inventory_p_categor_607069_idx'), models.Index(fields=['quantity_in_stock'], name='inventory_p_quantit_63a82b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity_in_stock__gte', 0)), name='product_quantity_nonnegative'), models.UniqueConstraint(fields=('name', 'category'), name='unique_product_in_category')],
            },
        ),
    ]
