# Generated by Django 5.2.4 on 2025-08-26 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_supplier'),
        ('purchases', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'In'), ('OUT', 'Out')], help_text="Type of movement: 'IN' for purchases, 'OUT' for sales.", max_length=3)),
                ('quantity', models.PositiveIntegerField(help_text='The quantity of the product moved.')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='The date and time of the stock movement.')),
                ('product', models.ForeignKey(help_text='The product whose stock was moved.', on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='inventory.product')),
                ('related_purchase', models.ForeignKey(blank=True, help_text='Reference to the purchase transaction, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchases.purchase')),
                ('related_sale', models.ForeignKey(blank=True, help_text='Reference to the sale transaction, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.sale')),
            ],
            options={
                'verbose_name_plural': 'Stock Movements',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['product'], name='stock_stock_product_e1ff8e_idx'), models.Index(fields=['timestamp'], name='stock_stock_timesta_fcaf16_idx')],
            },
        ),
    ]
